name: docker-build-push


on:
  workflow_dispatch:
    # Change to NOT push automatically -> want to create a branch and then merge after testing (will see this in github actions)
    # This DEPLOYS commits STRAIGHT to main branch (production)
  push:
    branches:
      - 'main'

env:
   FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  # creates image and pushes to docker hub
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:API"
          push: true
          tags: numanm21/mscdatingapp:latest
      # pushes to fly.io
  deploy:
    needs: docker # waits for docker job to finish
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        